general:
  output_folder: ./outputs/
  inference_period: 1
  # input_left: 0
  # input_top: 0
  # input_width: 289
  # input_height: 241

yolo_generic:
  detection_threshold: 0.5
  nms_threshold: 0.5
  distance_threshold: 1
  min_size: 32

yolo_darknet:  # Config specific to original darknet implementation (detector_darknet.py)
  darknet_path: ../yolo/darknet/  # Path with libdarknet.so
  config_file: ./yolov4.cfg
  data_file: ./coco.data
  weights_file: ./yolov4.weights

yolo_pytorch:
  repo_path: ../yolo/pytorch-YOLOv4
  config_file: ./integrations/yolo/yolov4-facemask.cfg
  names_file: ./integrations/yolo/obj.names
  weights_file: ./yolov4-facemask_final.weights
  use_cuda: true

yolo_trt:
  names_file: ./integrations/yolo/obj.names
  engine_file: ./yolov4-facemask.trt
  use_cuda: true

debug:
  draw_detections: true
  draw_tracking_ids: true
  draw_tracking_debug: false
  draw_predictions: true
  profiler: true
